### ISSUE TITLE
KDE Store?

### ISSUE THREAD

**Issue by afettouhi** [liujed/plasma-applet-rss-feeds#1]
Just saw this. Many thanks for the port to Plasma 6. Any plans to put up on the KDE Store?

**Comment by liujed** [comment]
I tried, but it requires an account at opendesktop.org, and account registration there doesn't appear to be working. Nothing happens when I click the **Register** button after filling out the registration form. I'll try again in a few days.

**Comment by liujed** [comment]
Turns out my ad blocker was interfering with the registration page. It's up on the KDE Store now: https://store.kde.org/p/2145065. It's not showing up yet on Plasma's "Get New Widgets" dialog, though. I'll keep an eye on it.

**Comment by afettouhi** [comment]
Cool, thanks for putting it up there.

**Comment by liujed** [comment]
No problem!

Confirmed that it's available in the "Get New Widgets" dialog. Installed it successfully.
