### ISSUE TITLE
Extremely high GPU load when feed can not be fetched (rotating gear)

### ISSUE THREAD

**Issue by olifre** [liujed/plasma-applet-rss-feeds#4]
Thanks for providing a Plasma 6 compatible version! 

When adding two RSS feed widgets to my desktop using a feed which can not be fetched (e.g. laptop is offline and can not contact the server), a rotating wheel is shown for both, as expected. 

CPU load remains normal, but checking with an iGPU (Haswell generation) with `intel_gpu_top`, the GPU uses 80-90 % of render time on an idle desktop instead of 5-9 %. 

This causes about 50 % reduction in battery runtime on my system, as the CPU can not enter any package C state anymore as the iGPU has zero idle time. 

It would be nice if the rotating wheel could be turned off / replaced by something non-animated to reduce power draw ;-).

**Comment by olifre** [comment]
@liujed Many thanks for the quick extension of that functionality — for me, it makes the difference between ~2 hours or ~3,5 hours of battery life on an idle desktop. Thanks again! :+1: :rocket:

**Comment by liujed** [comment]
Of course! 😄
